config/routes.rb
Rails.application.routes.draw do

  get "/pages/about" => "pages#about", as: :about
  get "/pages/contact" => "pages#contact", as: :contact

  #  get "/posts" => "posts#index", as: :posts
  #  post "/posts" => "posts#create"
  #  get "/post/:id" => "posts#show", as: :post
  #  patch "/post/:id" => "posts#update"
  #  delete "/post/:id" => "posts#destroy"
  #  get "/posts/new" => "posts#new", as: :new_post
  #  get "post/:id/edit" => "posts#edit", as: :edit_post

  root "posts#index"
  resources :posts

  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

	validates :title, presence: true
	validates :body, presence: true

	validates :title, length: {minimum: 5}
	validates :body, length: {minimum: 20}

	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)

		flash[:notice] = "Comment has been created"
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		flash[:notice] = "Comment successfully destroyed"
		redirect_to post_path(@post)

	end

	private

	def comment_params
		params.require(:comment).permit(:name, :body)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		
	end

	def contact
		
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	def index
		@posts = Post.all.order("created_at DESC")
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:notice] = "Post successfully created"
			redirect_to post_path(@post)
		else
			render :new
		end


	end

	def show
		
	end

	def edit
		
	end

	def update
		
		if @post.update(post_params)
			flash[:notice] = "Post successfully Updated"
			redirect_to post_path(@post)
		else
			render :edit
		end
	end

	def destroy
		
		@post.destroy

		flash[:notice] = "Post successfully destroyed"
		redirect_to posts_path
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-default">
	<div class="panel-heading>"><%= comment.name %></div>
	<div class="panel-body">
		<%= comment.body %>
		<p><%= link_to "delete", [comment.post, comment], method: :delete, data: {confirm: "are you sure?"} %></p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Custom Fonts -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "My Awesome Blog", root_path, class: "navbar-brand" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                    	<%= link_to "Create New Post", new_post_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

 <% if flash[:notice] %>
    <div><%= flash[:notice] %></div>
 <% end %>

<%= yield %>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; My Awesome Blog 2015</p>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

app/views/pages/about.html.erb
<h1> Hi Welcome to the About page</h1>

<div class="manually written">
	<a href="/pages/about">About Us</a>
	<a href="/pages/contact">Contact Us</a>
</div>

<div class="genereated">
	<%= link_to("About",  about_path ) %>
	<%= link_to("Contact Us", contact_path ) %>
</div>

<div>

	<%= image_tag("cat.jpg", alt: "This is a cat") %>

</div>

<div class="dog_image">

</div>

app/views/pages/contact.html.erb
<h1> Hi Welcome to the contact page</h1>

<a href="/pages/about">About Us</a>
<a href="/pages/contact">Contact Us</a>

app/views/posts/_form.html.erb
	<%=  form_for @post do |f|%>

	<% if @post.errors.any? %>
		<ul>
			<% @post.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        	<%= f.label :title %>
                            <%= f.text_field :title, class: "form-control", placeholder: "Title"  %>
                            <p class="help-block text-danger"></p>

                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <%= f.label :body %>
                            <%= f.text_area :body, class: "form-control", placeholder: "Body" %>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                        	<%= f.submit class: "btn btn-default" %>
                        </div>
                    </div>
	<% end %>

app/views/posts/edit.html.erb
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header header2">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>
                        	<%= @post.title %>
						</h1>
                        <!-- <h2 class="subheading">Problems look mighty small from 150 miles up</h2>-->
                        <span class="meta">
							<%= link_to "back", posts_path %> |
							<%= link_to "delete", post_path(@post), method: :delete, data: {confirm: "Are you being a dick?"} %>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
					<%= render "form" %>
                </div>
            </div>
        </div>
    </article>   

app/views/posts/index.html.erb
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header header1">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>My Awesome Blog</h1>
                        <hr class="small">
                        <span class="subheading">I made this blog myself.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

			<% @posts.each do |post|    %>

                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                        	<%= link_to post.title, post_path(post) %>
                        </h2>
                        <!-- <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3> -->
                    </a>
                    <p class="post-meta">
                    	<%= link_to "edit", edit_post_path(post) %> |
						<%= link_to "delete", post_path(post), method: :delete, data: {confirm: "Are you being a dick?"} %>
					</p>
                </div>
                <hr>
			
			<% end %>

            </div>
        </div>
    </div>

app/views/posts/new.html.erb
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header header3">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Create New Blog Post</h1>
                        <hr class="small">
                        <span class="subheading">Use the form below to create a new blog post.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            	<%= render "form"%>
            </div>
        </div>
    </div>
<!--<h1>Create New Blog Post   <%= link_to "back", posts_path %></h1>-->

app/views/posts/show.html.erb
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header header2">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>
                        	<%= @post.title %>
						</h1>
                        <!-- <h2 class="subheading">Problems look mighty small from 150 miles up</h2>-->
                        <span class="meta">
							<%= link_to "edit", edit_post_path(@post)%> |
							<%= link_to "delete", post_path(@post), method: :delete, data: {confirm: "Are you being a dick?"} %>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p>
						<%= @post.body %>
                    </p>

						<% if @post.comments.count > 0 %>
							<hr>
							<h2>All Comments:</h2>
							<hr>
							<%= render @post.comments.order("created_at DESC") %>
						<% end %>
                </div>
            </div>
        </div>
    </article>   

<div class="lightbg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

            	<h2>Leave a Comment:</h2>
				<%= form_for [@post, @post.comments.build] do |f| %>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <%= f.label :name %>
                            <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <%= f.label :body %>
                            <%= f.text_area :body, class: "form-control", placeholder: "Message" %>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                        	<%= f.submit class: "btn btn-default" %>
                        </div>
                    </div>
				<% end %>
            </div>
        </div>
    </div>
</div>